"""
Vision Runtime Module

Provides computer vision capabilities including image classification,
object detection, segmentation, OCR, face detection/recognition,
and image generation/editing.
"""

from runtime.vision.module import (
    VisionModule,
    ImageData,
    ImageFormat,
    VisionModel,
    VisionTask,
    BoundingBox,
    ClassificationResult,
    DetectionResult,
    SegmentationResult,
    OCRResult,
    FaceDetection,
    FaceDetectionResult,
    FaceRecognitionResult,
    PoseEstimationResult,
    ImageGenerationResult,
    ImageEditResult,
    EmbeddingResult,
    VQAResult,
    CaptionResult,
    VisionBackend,
    ClassificationBackend,
    DetectionBackend,
    SegmentationBackend,
    OCRBackend,
    FaceBackend,
    GenerationBackend,
    EditingBackend,
    EmbeddingBackend,
    VQABackend,
    CaptionBackend,
)

__all__ = [
    "VisionModule",
    "ImageData",
    "ImageFormat",
    "VisionModel",
    "VisionTask",
    "BoundingBox",
    "ClassificationResult",
    "DetectionResult",
    "SegmentationResult",
    "OCRResult",
    "FaceDetection",
    "FaceDetectionResult",
    "FaceRecognitionResult",
    "PoseEstimationResult",
    "ImageGenerationResult",
    "ImageEditResult",
    "EmbeddingResult",
    "VQAResult",
    "CaptionResult",
    "VisionBackend",
    "ClassificationBackend",
    "DetectionBackend",
    "SegmentationBackend",
    "OCRBackend",
    "FaceBackend",
    "GenerationBackend",
    "EditingBackend",
    "EmbeddingBackend",
    "VQABackend",
    "CaptionBackend",
]