"""
Skill Runtime Module

Provides skill management, skill discovery, skill execution,
skill marketplace, and skill composition.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Set
import asyncio
import inspect
import logging
import uuid

from runtime.modules import (
    RuntimeModule,
    ModuleMetadata,
    ModuleState,
)

logger = logging.getLogger(__name__)


class SkillType(Enum):
    """Skill type."""
    BUILTIN = "builtin"       # Core system skills
    CUSTOM = "custom"         # User-defined skills
    INTEGRATION = "integration"  # External service integrations
    COMPOSITE = "composite"   # Composed from other skills
    AI_GENERATED = "ai_generated"  # Generated by LLM


class SkillStatus(Enum):
    """Skill status."""
    DRAFT = "draft"
    ACTIVE = "active"
    DEPRECATED = "deprecated"
    ARCHIVED = "archived"
    DISABLED = "disabled"


class SkillCategory(Enum):
    """Skill category."""
    AUTOMATION = "automation"
    DATA_PROCESSING = "data_processing"
    COMMUNICATION = "communication"
    ANALYSIS = "analysis"
    CREATIVE = "creative"
    DEVELOPMENT = "development"
    OPERATIONS = "operations"
    SECURITY = "security"
    CUSTOM = "custom"


@dataclass
class SkillParameter:
    """Skill parameter definition."""
    name: str
    type: str  # JSON Schema type
    description: str = ""
    required: bool = True
    default: Any = None
    enum: List[Any] = field(default_factory=list)
    examples: List[Any] = field(default_factory=list)


@dataclass
class SkillResult:
    """Skill execution result."""
    success: bool
    data: Any = None
    error: Optional[str] = None
    execution_time_ms: float = 0
    metadata: Dict[str, Any] = field(default_factory=dict)
    logs: List[str] = field(default_factory=list)


@dataclass
class Skill:
    """Skill definition."""
    skill_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    name: str = ""
    description: str = ""
    skill_type: SkillType = SkillType.CUSTOM
    category: SkillCategory = SkillCategory.CUSTOM
    status: SkillStatus = SkillStatus.DRAFT
    version: str = "1.0.0"
    author: str = ""
    tags: List[str] = field(default_factory=list)
    parameters: List[SkillParameter] = field(default_factory=list)
    returns: Dict[str, Any] = field(default_factory=dict)  # JSON Schema
    implementation: str = ""  # Code, reference, or composite definition
    dependencies: List[str] = field(default_factory=list)  # Other skill IDs
    required_permissions: List[str] = field(default_factory=list)
    timeout_seconds: int = 300
    rate_limit: Optional[int] = None  # calls per minute
    examples: List[Dict[str, Any]] = field(default_factory=list)
    documentation: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)
    published_at: Optional[datetime] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "skill_id": self.skill_id,
            "name": self.name,
            "description": self.description,
            "skill_type": self.skill_type.value,
            "category": self.category.value,
            "status": self.status.value,
            "version": self.version,
            "author": self.author,
            "tags": self.tags,
            "parameters": [p.__dict__ for p in self.parameters],
            "returns": self.returns,
            "implementation": self.implementation,
            "dependencies": self.dependencies,
            "required_permissions": self.required_permissions,
            "timeout_seconds": self.timeout_seconds,
            "rate_limit": self.rate_limit,
            "examples": self.examples,
            "documentation": self.documentation,
            "metadata": self.metadata,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
            "published_at": self.published_at.isoformat() if self.published_at else None
        }


class SkillExecutor(ABC):
    """Abstract skill executor."""

    @property
    @abstractmethod
    def skill_type(self) -> SkillType:
        pass

    @abstractmethod
    async def execute(self, skill: Skill, parameters: Dict[str, Any], context: Dict[str, Any]) -> SkillResult:
        pass

    @abstractmethod
    async def validate(self, skill: Skill) -> bool:
        pass


class FunctionSkillExecutor(SkillExecutor):
    """Execute Python function skills."""

    @property
    def skill_type(self) -> SkillType:
        return SkillType.CUSTOM

    async def execute(self, skill: Skill, parameters: Dict[str, Any], context: Dict[str, Any]) -> SkillResult:
        start = datetime.utcnow()
        try:
            # Get function from implementation
            func = self._get_function(skill.implementation)
            if not func:
                return SkillResult(False, error="Function not found")

            # Execute
            if inspect.iscoroutinefunction(func):
                result = await func(**parameters, context=context)
            else:
                result = func(**parameters, context=context)

            execution_time = (datetime.utcnow() - start).total_seconds() * 1000
            return SkillResult(True, data=result, execution_time_ms=execution_time)
        except Exception as e:
            execution_time = (datetime.utcnow() - start).total_seconds() * 1000
            return SkillResult(False, error=str(e), execution_time_ms=execution_time)

    async def validate(self, skill: Skill) -> bool:
        return self._get_function(skill.implementation) is not None

    def _get_function(self, implementation: str) -> Optional[Callable]:
        """Get function from implementation string."""
        # Implementation could be "module:function" or direct function reference
        if ":" in implementation:
            module_name, func_name = implementation.split(":", 1)
            try:
                module = __import__(module_name, fromlist=[func_name])
                return getattr(module, func_name)
            except Exception:
                return None
        return None


class CompositeSkillExecutor(SkillExecutor):
    """Execute composite skills (workflows of other skills)."""

    @property
    def skill_type(self) -> SkillType:
        return SkillType.COMPOSITE

    async def execute(self, skill: Skill, parameters: Dict[str, Any], context: Dict[str, Any]) -> SkillResult:
        start = datetime.utcnow()
        try:
            # Parse composite definition
            composite = json.loads(skill.implementation)
            steps = composite.get("steps", [])

            results = {}
            for step in steps:
                step_skill_id = step.get("skill_id")
                step_params = step.get("parameters", {})

                # Resolve parameter references
                resolved_params = self._resolve_params(step_params, parameters, results)

                # Execute dependency skill
                skill_module = context.get("skill_module")
                if not skill_module:
                    return SkillResult(False, error="Skill module not available")

                result = await skill_module.execute_skill(step_skill_id, resolved_params)
                if not result.success:
                    return SkillResult(False, error=f"Step {step.get('name')}: {result.error}")

                results[step.get("name", step_skill_id)] = result.data

            execution_time = (datetime.utcnow() - start).total_seconds() * 1000
            return SkillResult(True, data=results, execution_time_ms=execution_time)

        except Exception as e:
            execution_time = (datetime.utcnow() - start).total_seconds() * 1000
            return SkillResult(False, error=str(e), execution_time_ms=execution_time)

    def _resolve_params(self, params: Dict, input_params: Dict, step_results: Dict) -> Dict[str, Any]:
        """Resolve parameter references like ${input.param} or ${step.result.field}."""
        resolved = {}
        for key, value in params.items():
            if isinstance(value, str):
                # Replace ${input.xxx} with input_params
                if value.startswith("${input."):
                    ref = value[8:-1]  # Remove ${input. and }
                    resolved[key] = input_params.get(ref, value)
                # Replace ${step.xxx.yyy} with step results
                elif value.startswith("${step."):
                    parts = value[7:-1].split(".")
                    step_name = parts[0]
                    if step_name in step_results:
                        data = step_results[step_name]
                        for part in parts[1:]:
                            if isinstance(data, dict):
                                data = data.get(part)
                            else:
                                data = None
                                break
                        resolved[key] = data if data is not None else value
                    else:
                        resolved[key] = value
                else:
                    resolved[key] = value
            else:
                resolved[key] = value
        return resolved

    async def validate(self, skill: Skill) -> bool:
        try:
            json.loads(skill.implementation)
            return True
        except:
            return False


class SkillModule(RuntimeModule):
    """
    Skill management module.

    Provides:
    - Skill registration and discovery
    - Skill execution with multiple executor types
    - Skill versioning and dependencies
    - Skill marketplace (publish, subscribe, install)
    - Skill composition and chaining
    - Rate limiting and permissions
    """

    @property
    def metadata(self) -> ModuleMetadata:
        return ModuleMetadata(
            name="skill",
            version="1.0.0",
            description="Skill management and execution engine",
            author="AIPENSA",
            dependencies=["tool", "workflow"],
            provides=["skill_registry", "skill_execution", "skill_composition", "skill_marketplace"],
            tags={"skill", "automation", "plugin", "marketplace", "composition"}
        )

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        super().__init__(config)
        self._skills: Dict[str, Skill] = {}
        self._executors: Dict[SkillType, SkillExecutor] = {}
        self._skill_cache: Dict[str, Callable] = {}
        self._config: Dict[str, Any] = {}
        self._marketplace_index: Dict[str, List[Skill]] = defaultdict(list)
        self._installed_skills: Dict[str, Set[str]] = defaultdict(set)  # user_id -> {skill_id}

    async def initialize(self, runtime: "Runtime", config: Dict[str, Any]) -> None:
        """Initialize skill module."""
        self._runtime = runtime
        self._config = {**self._config, **config}

        # Register default executors
        self._executors[SkillType.CUSTOM] = FunctionSkillExecutor()
        self._executors[SkillType.COMPOSITE] = CompositeSkillExecutor()
        self._executors[SkillType.BUILTIN] = FunctionSkillExecutor()

        # Load built-in skills
        await self._load_builtin_skills()

        # Load skills from config
        for skill_data in self._config.get("skills", []):
            skill = Skill(**skill_data)
            await self.register_skill(skill)

        self.state = ModuleState.INITIALIZED
        logger.info(f"Skill module initialized with {len(self._skills)} skills")

    async def start(self) -> None:
        self.state = ModuleState.RUNNING
        logger.info("Skill module started")

    async def stop(self) -> None:
        self.state = ModuleState.STOPPED
        logger.info("Skill module stopped")

    async def cleanup(self) -> None:
        self._skills.clear()
        self._executors.clear()
        self._skill_cache.clear()
        self.state = ModuleState.UNINITIALIZED
        logger.info("Skill module cleaned up")

    async def health_check(self) -> Dict[str, Any]:
        return {
            "module": "skill",
            "status": self.state.value,
            "healthy": self.state == ModuleState.RUNNING,
            "total_skills": len(self._skills),
            "active_skills": len([s for s in self._skills.values() if s.status == SkillStatus.ACTIVE]),
            "executors": list(self._executors.keys())
        }

    async def _load_builtin_skills(self) -> None:
        """Load built-in system skills."""
        builtin_skills = [
            Skill(
                skill_id="builtin.echo",
                name="Echo",
                description="Echo input back",
                skill_type=SkillType.BUILTIN,
                category=SkillCategory.AUTOMATION,
                status=SkillStatus.ACTIVE,
                author="system",
                parameters=[
                    SkillParameter(name="message", type="string", description="Message to echo")
                ],
                returns={"type": "string"},
                implementation="runtime.skills.builtin:echo",
                timeout_seconds=10
            ),
            Skill(
                skill_id="builtin.sleep",
                name="Sleep",
                description="Pause execution",
                skill_type=SkillType.BUILTIN,
                category=SkillCategory.AUTOMATION,
                status=SkillStatus.ACTIVE,
                author="system",
                parameters=[
                    SkillParameter(name="seconds", type="number", description="Seconds to sleep"),
                    SkillParameter(name="milliseconds", type="integer", description="Milliseconds to sleep", required=False)
                ],
                returns={"type": "object"},
                implementation="runtime.skills.builtin:sleep",
                timeout_seconds=60
            ),
        ]

        for skill in builtin_skills:
            self._skills[skill.skill_id] = skill

    # Skill Registration
    async def register_skill(self, skill: Skill) -> Skill:
        """Register a new skill."""
        if skill.skill_id in self._skills:
            existing = self._skills[skill.skill_id]
            if existing.version >= skill.version:
                raise ValueError(f"Skill {skill.name} version {skill.version} already exists or is older")

        # Validate skill
        executor = self._executors.get(skill.skill_type)
        if executor and not await executor.validate(skill):
            raise ValueError(f"Skill validation failed for {skill.skill_id}")

        skill.updated_at = datetime.utcnow()
        if skill.status == SkillStatus.ACTIVE and not skill.published_at:
            skill.published_at = datetime.utcnow()

        self._skills[skill.skill_id] = skill

        # Index for marketplace
        if skill.status == SkillStatus.ACTIVE:
            self._marketplace_index[skill.category.value].append(skill)

        logger.info(f"Registered skill: {skill.skill_id} - {skill.name}")
        return skill

    async def get_skill(self, skill_id: str) -> Optional[Skill]:
        """Get skill by ID."""
        return self._skills.get(skill_id)

    async def update_skill(self, skill: Skill) -> Skill:
        """Update skill."""
        if skill.skill_id not in self._skills:
            raise ValueError(f"Skill not found: {skill.skill_id}")

        skill.updated_at = datetime.utcnow()
        self._skills[skill.skill_id] = skill
        return skill

    async def delete_skill(self, skill_id: str) -> bool:
        """Delete skill."""
        if skill_id in self._skills:
            skill = self._skills.pop(skill_id)
            # Remove from marketplace index
            if skill.category.value in self._marketplace_index:
                self._marketplace_index[skill.category.value] = [
                    s for s in self._marketplace_index[skill.category.value]
                    if s.skill_id != skill_id
                ]
            return True
        return False

    async def list_skills(
        self,
        category: Optional[SkillCategory] = None,
        status: Optional[SkillStatus] = None,
        skill_type: Optional[SkillType] = None,
        tags: Optional[List[str]] = None,
        author: Optional[str] = None,
        limit: int = 100,
        offset: int = 0
    ) -> List[Skill]:
        """List skills with filtering."""
        skills = list(self._skills.values())

        if category:
            skills = [s for s in skills if s.category == category]
        if status:
            skills = [s for s in skills if s.status == status]
        if skill_type:
            skills = [s for s in skills if s.skill_type == skill_type]
        if tags:
            skills = [s for s in skills if any(t in s.tags for t in tags)]
        if author:
            skills = [s for s in skills if s.author == author]

        skills.sort(key=lambda s: s.updated_at, reverse=True)
        return skills[offset:offset + limit]

    # Skill Execution
    async def execute_skill(
        self,
        skill_id: str,
        parameters: Dict[str, Any],
        context: Optional[Dict[str, Any]] = None
    ) -> SkillResult:
        """Execute a skill."""
        skill = self._skills.get(skill_id)
        if not skill:
            return SkillResult(False, error=f"Skill not found: {skill_id}")

        if skill.status != SkillStatus.ACTIVE:
            return SkillResult(False, error=f"Skill not active: {skill.status.value}")

        # Check permissions
        context = context or {}
        auth_module = self._runtime.modules.get("authentication")
        user_id = context.get("user_id")
        if user_id and skill.required_permissions:
            for perm in skill.required_permissions:
                if auth_module and not await auth_module.execute("check_permission", user_id=user_id, permission=perm):
                    return SkillResult(False, error=f"Missing permission: {perm}")

        # Get executor
        executor = self._executors.get(skill.skill_type, self._executors.get(SkillType.CUSTOM))

        # Add skill module to context for composite skills
        context["skill_module"] = self

        # Execute with timeout
        try:
            execution = asyncio.wait_for(
                executor.execute(skill, parameters, context),
                timeout=skill.timeout_seconds
            )
            result = await execution
        except asyncio.TimeoutError:
            result = SkillResult(False, error=f"Skill execution timed out ({skill.timeout_seconds}s)")
        except Exception as e:
            result = SkillResult(False, error=str(e))

        return result

    async def execute_skill_chain(
        self,
        skill_ids: List[str],
        initial_parameters: Dict[str, Any],
        context: Optional[Dict[str, Any]] = None
    ) -> List[SkillResult]:
        """Execute a chain of skills, passing results as parameters to next."""
        results = []
        current_params = initial_parameters.copy()

        for skill_id in skill_ids:
            result = await self.execute_skill(skill_id, current_params, context)
            results.append(result)

            if not result.success:
                break

            # Merge result data into parameters for next skill
            if result.data and isinstance(result.data, dict):
                current_params.update(result.data)

        return results

    # Skill Composition
    async def create_composite_skill(
        self,
        name: str,
        description: str,
        steps: List[Dict[str, Any]],
        author: str = "",
        category: SkillCategory = SkillCategory.AUTOMATION,
        parameters: Optional[List[SkillParameter]] = None,
        returns: Optional[Dict[str, Any]] = None
    ) -> Skill:
        """Create a composite skill from steps."""
        composite_def = {"steps": steps}
        implementation = json.dumps(composite_def)

        skill = Skill(
            name=name,
            description=description,
            skill_type=SkillType.COMPOSITE,
            category=category,
            author=author,
            parameters=parameters or [],
            returns=returns or {"type": "object"},
            implementation=implementation,
            status=SkillStatus.ACTIVE
        )

        return await self.register_skill(skill)

    # Marketplace
    async def publish_skill(self, skill_id: str) -> bool:
        """Publish skill to marketplace."""
        skill = self._skills.get(skill_id)
        if not skill:
            return False

        skill.status = SkillStatus.ACTIVE
        skill.published_at = datetime.utcnow()
        skill.updated_at = datetime.utcnow()

        self._skills[skill_id] = skill
        self._marketplace_index[skill.category.value].append(skill)
        return True

    async def unpublish_skill(self, skill_id: str) -> bool:
        """Unpublish skill from marketplace."""
        skill = self._skills.get(skill_id)
        if not skill:
            return False

        skill.status = SkillStatus.DRAFT
        skill.updated_at = datetime.utcnow()

        self._skills[skill_id] = skill
        if skill.category.value in self._marketplace_index:
            self._marketplace_index[skill.category.value] = [
                s for s in self._marketplace_index[skill.category.value]
                if s.skill_id != skill_id
            ]
        return True

    async def browse_marketplace(
        self,
        category: Optional[SkillCategory] = None,
        tags: Optional[List[str]] = None,
        search: Optional[str] = None,
        limit: int = 50,
        offset: int = 0
    ) -> List[Skill]:
        """Browse marketplace skills."""
        skills = []

        if category:
            skills = self._marketplace_index.get(category.value, [])
        else:
            for cat_skills in self._marketplace_index.values():
                skills.extend(cat_skills)

        if tags:
            skills = [s for s in skills if any(t in s.tags for t in tags)]
        if search:
            search_lower = search.lower()
            skills = [s for s in skills if search_lower in s.name.lower() or search_lower in s.description.lower()]

        skills.sort(key=lambda s: s.published_at or datetime.min, reverse=True)
        return skills[offset:offset + limit]

    async def install_skill(self, user_id: str, skill_id: str) -> bool:
        """Install skill for user (alias to track usage)."""
        if skill_id not in self._skills:
            return False

        self._installed_skills[user_id].add(skill_id)
        return True

    async def uninstall_skill(self, user_id: str, skill_id: str) -> bool:
        """Uninstall skill for user."""
        if user_id in self._installed_skills:
            self._installed_skills[user_id].discard(skill_id)
            return True
        return False

    async def get_installed_skills(self, user_id: str) -> List[Skill]:
        """Get user's installed skills."""
        skill_ids = self._installed_skills.get(user_id, set())
        return [self._skills[sid] for sid in skill_ids if sid in self._skills]

    # Module Operations
    async def execute(self, operation: str, **kwargs) -> Any:
        mapping = {
            "register": self.register_skill,
            "get": self.get_skill,
            "update": self.update_skill,
            "delete": self.delete_skill,
            "list": self.list_skills,
            "execute": self.execute_skill,
            "execute_chain": self.execute_skill_chain,
            "create_composite": self.create_composite_skill,
            "publish": self.publish_skill,
            "unpublish": self.unpublish_skill,
            "browse_marketplace": self.browse_marketplace,
            "install": self.install_skill,
            "uninstall": self.uninstall_skill,
            "get_installed": self.get_installed_skills,
        }
        if operation in mapping:
            return await mapping[operation](**kwargs)
        raise NotImplementedError(f"Operation '{operation}' not supported")


import json
from collections import defaultdict

__all__ = [
    "SkillModule",
    "SkillExecutor",
    "FunctionSkillExecutor",
    "CompositeSkillExecutor",
    "Skill",
    "SkillParameter",
    "SkillResult",
    "SkillType",
    "SkillStatus",
    "SkillCategory",
]